package rock_paper_surprise;

import java.io.*;
import static org.junit.Assert.*;
import org.junit.Before;
import org.junit.Test;

/**
 * // -------------------------------------------------------------------------
 * /** Test class for the Game class
 * 
 * @author Chris Tricarico (christ07)
 * @version Sept., 2026
 */
public class GameTest {

    private Player mockPlayer;
    private Game game;
    
    @Before
    public void setUp() {
        // Creating a valid player instance for the game constructor
        mockPlayer = new Player("TestUser");
        game = new Game(mockPlayer);
    }


    /**
     * Test that the game initializes without throwing errors.
     */
    @Test
    public void testGameConstructor() {
        assertNotNull(game);
    }


    /**
     * Test that getResponse() never returns null.
     */
    @Test
    public void testGetResponseNotNull() {
        for (int i = 0; i < 100; i++) {
            Option response = game.getResponse();
            assertNotNull(response);
            assertNotNull(response.getName());
        }
    }


    /**
     * Test that getResponse() matches the expected probability distribution.
     * Uses a large sample size to satisfy statistical significance.
     */
    @Test
    public void testGetResponseProbabilityDistribution() {
        int rockCount = 0;
        int paperCount = 0;
        int scissorsCount = 0;
        int surpriseCount = 0;

        int totalIterations = 100_000;

        for (int i = 0; i < totalIterations; i++) {
            Option response = game.getResponse();
            // Standardizing comparison to ignore potential casing differences
            String name = response.getName().toLowerCase();

            switch (name) {
                case "rock":
                    rockCount++;
                    break;
                case "paper":
                    paperCount++;
                    break;
                case "scissors":
                    scissorsCount++;
                    break;
                case "surprise":
                    surpriseCount++;
                    break;
                default:
                    fail("Unexpected option generated by computer: " + response
                        .getName());
            }
        }

        // Calculate actual percentages
        double rockProb = (double)rockCount / totalIterations;
        double paperProb = (double)paperCount / totalIterations;
        double scissorsProb = (double)scissorsCount / totalIterations;
        double surpriseProb = (double)surpriseCount / totalIterations;

        // Allowing a +/- 1.5% margin of error due to random variance
        double allowedDelta = 0.015;

        assertEquals(0.30, rockProb, allowedDelta);
        assertEquals(0.30, paperProb, allowedDelta);
        assertEquals(0.30, scissorsProb, allowedDelta);
        assertEquals(0.10, surpriseProb, allowedDelta);
    }
}
